name: tests

on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: |
          uv sync --all-extras --dev

      - name: Style checking
        if: ${{ matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest' }}
        run: |
          uv run ruff check src tests
          uv run ruff format --check src tests

      - name: Type checking
        if: ${{ matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest' }}
        run: |
          uv run mypy src

      - name: Run tests
        run: |
          uv run coverage run -m unittest
          uv run coverage report

      - name: Upload coverage to Codecov
        if: ${{ github.event_name != 'pull_request_target' && matrix.os == 'ubuntu-latest' }}
        run: |
          uv run codecov
